// File generated by FlutterFire CLI.
// This is a template file. You need to configure Firebase in your Firebase Console first.
// Then run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7xCvb6TWxRLiI5iBX3ESEoXIphSHN0s',
    appId: '1:881776104506:web:27fa7454a14071785dd103',
    messagingSenderId: '881776104506',
    projectId: 'siakad-sekolah-c9a69',
    authDomain: 'siakad-sekolah-c9a69.firebaseapp.com',
    storageBucket: 'siakad-sekolah-c9a69.firebasestorage.app',
    measurementId: 'G-S3VYL3HX09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QAVHsFPPhgL9meTslT6ZUtJrfZ4WYZM',
    appId: '1:881776104506:android:dae76dba5a1cf3b95dd103',
    messagingSenderId: '881776104506',
    projectId: 'siakad-sekolah-c9a69',
    storageBucket: 'siakad-sekolah-c9a69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBprbSrmFkstrEwABSSccBOH-mNb28mogQ',
    appId: '1:881776104506:ios:af7d27b5e1d39b5e5dd103',
    messagingSenderId: '881776104506',
    projectId: 'siakad-sekolah-c9a69',
    storageBucket: 'siakad-sekolah-c9a69.firebasestorage.app',
    iosBundleId: 'com.example.siakadSekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBprbSrmFkstrEwABSSccBOH-mNb28mogQ',
    appId: '1:881776104506:ios:af7d27b5e1d39b5e5dd103',
    messagingSenderId: '881776104506',
    projectId: 'siakad-sekolah-c9a69',
    storageBucket: 'siakad-sekolah-c9a69.firebasestorage.app',
    iosBundleId: 'com.example.siakadSekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV7xCvb6TWxRLiI5iBX3ESEoXIphSHN0s',
    appId: '1:881776104506:web:6be7aa50da3de9835dd103',
    messagingSenderId: '881776104506',
    projectId: 'siakad-sekolah-c9a69',
    authDomain: 'siakad-sekolah-c9a69.firebaseapp.com',
    storageBucket: 'siakad-sekolah-c9a69.firebasestorage.app',
    measurementId: 'G-G72TTCMJM6',
  );

}